# Generated by Django 6.0 on 2025-12-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Family',
            },
        ),
        migrations.CreateModel(
            name='TypeofRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TypeofRelationship',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('maidenName', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('yearOfDeath', models.IntegerField(blank=True, null=True)),
                ('monthOfDeath', models.IntegerField(blank=True, null=True)),
                ('dayOfDeath', models.IntegerField(blank=True, null=True)),
                ('yearOfBirth', models.IntegerField(blank=True, null=True)),
                ('monthOfBirth', models.IntegerField(blank=True, null=True)),
                ('dayOfBirth', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField()),
                ('school', models.TextField(blank=True, null=True)),
                ('college', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('work', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fio', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('isActive', models.IntegerField(default=1)),
                ('isAlive', models.IntegerField(default=1)),
                ('marriageinfo', models.TextField(blank=True, null=True)),
                ('idCity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.city')),
                ('idCityOfBirth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natives', to='api.city')),
                ('idCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.country')),
                ('idCountryOfBirth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natives', to='api.country')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='FamilyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFamily', models.ForeignKey(blank=True, db_column='idFamily', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.family')),
                ('idPerson', models.ForeignKey(blank=True, db_column='idPerson', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'db_table': 'FamilyConnection',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='idFamilyOwner',
            field=models.ForeignKey(blank=True, db_column='idFamilyOwner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.person'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idCountry', models.ForeignKey(blank=True, db_column='idCountry', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='idRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.region'),
        ),
        migrations.AddField(
            model_name='person',
            name='idRegionOfBirth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natives', to='api.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='idRegion',
            field=models.ForeignKey(blank=True, db_column='idRegion', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromId', models.ForeignKey(blank=True, db_column='fromId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rel', to='api.person')),
                ('toId', models.ForeignKey(blank=True, db_column='toId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rel', to='api.person')),
                ('typeId', models.ForeignKey(blank=True, db_column='typeId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typeofrelationship')),
            ],
            options={
                'db_table': 'Relationships',
            },
        ),
    ]
